### ISSUE TITLE
React v15.3.2 giving dependency errors

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel-react#14]
Maybe have viewmodel be dependant on react 15.3.1 rather than ^15.3.1? Or if you can help me/us, how would we get rid of these errors? http://stackoverflow.com/questions/39692025/what-is-causing-the-npm-dependency-warning
Wait, might be answered here: 
http://stackoverflow.com/questions/37312749/warning-npm-peer-requirements-not-installed-react15-0-2-installed-react0-14?rq=1

**Comment by ManuelDeLeon** [comment]
The solution is to have a peer dependency on react, not a hard one. I don't
know which react is the lowest it works with, I think it's 15.2.0

On Oct 18, 2016 4:46 PM, "Fedor Parfenov" notifications@github.com wrote:

Closed #14 https://github.com/ManuelDeLeon/viewmodel-react/issues/14.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ManuelDeLeon/viewmodel-react/issues/14#event-828271343,
or mute the thread

**Comment by ManuelDeLeon** [comment]
I'll update it later tonight.

**Comment by fvpDev** [comment]
Well, I don't think it was a vm-react issue at all

**Comment by ManuelDeLeon** [comment]
Even then, it should be a peer dependency (It should work with the React version you have). Another reason is that it will help make it work with React-Native.

I just published 0.8.11 which has that change.
